name: Build Scratch Image

on:
  push:
    paths:
    - '.github/workflows/alpine.yml'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Docker Pull
      run: git clone --branch edge https://github.com/alpinelinux/docker-alpine.git

    - name: Docker Tag
      run: cd docker-alpine; for i in $(ls -d */); do cd $i; TAG_VALUE="${PWD##*/}"; docker build -t alpine:$TAG_VALUE .; cd ..; done;docker images
