name: Build Scratch Image

on:
  push:
    paths:
    - 'scratch/**'
    - '.github/workflows/scratch.yml'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Get original image from Docker Hub
    - name: Docker Pull
      run: docker tag scratch ghcr.io/${{ github.repository_owner }}/scratch
