name: Build Ubuntu Images

on:
  push:
    paths:
    - '.github/workflows/ubuntu.yml'
  schedule:
    - cron: '0 0 1 * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ubuntu
  GIT_REPO: https://github.com/tianon/docker-brew-ubuntu-core

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin

    - name: Clone Repository
      run: git clone $GIT_REPO

    - name: Trying to build Docker dist-i386 arch
      continue-on-error: true
      run: cd $(echo ${GIT_REPO} | rev | cut -d"/" -f1 | rev); git checkout $GIT_BRANCH; for i in $(ls -d */); do cd $i; VERSION="${PWD##*/}"; IMAGE_ID="$REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME:$VERSION"; docker buildx build --platform $IMG_ARCH -t $IMAGE_ID --load .; cd ..; done
      env:
        GIT_BRANCH: dist-i386
        IMG_ARCH: linux/386

    - name: Push images
      run: docker images; for i in $(docker images $REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME --format "{{.Repository}}:{{.Tag}}"); do docker push $i; done

    - name: Trying to build Docker dist-amd64 arch
      continue-on-error: true
      run: cd $(echo ${GIT_REPO} | rev | cut -d"/" -f1 | rev); git checkout $GIT_BRANCH; for i in $(ls -d */); do cd $i; VERSION="${PWD##*/}"; IMAGE_ID="$REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME:$VERSION"; docker buildx build --platform $IMG_ARCH -t $IMAGE_ID --load .; cd ..; done
      env:
        GIT_BRANCH: dist-amd64
        IMG_ARCH: linux/amd64
  
    - name: Push images
      run: docker images; for i in $(docker images $REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME --format "{{.Repository}}:{{.Tag}}"); do docker push $i; done
