name: Build Ubuntu Images

on:
  push:
    paths:
    - '.github/workflows/ubuntu.yml'
  schedule:
    - cron: '0 0 1 * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ubuntu

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin

    - name: Clone Repository, build and images
      run: git clone --branch $GIT_BRANCH $GIT_REPO; cd $(echo ${GIT_REPO} | rev | cut -d"/" -f1 | rev); for i in $(ls -d */); do cd $i; VERSION="${PWD##*/}"; IMAGE_ID="$REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME:$VERSION"; docker buildx build --platform $IMG_ARCH -t $IMAGE_ID --load .; cd ..; done
      env:
        GIT_REPO: https://github.com/tianon/docker-brew-ubuntu-core
        GIT_BRANCH: dist-i386
        IMG_ARCH: linux/386

    - name: Log in to registry
      run: pwd; ls; docker images